alter table public.questions
add column if not exists figure_url text;

delete from public.questions
where subject = 'ICAO Doc 8168';

insert into public.questions (
  subject,
  topic,
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option,
  explanation,
  source,
  figure_url
)
values
(
  $$ICAO Doc 8168$$,
  $$General requirements$$,
  $$A pilot is flying an instrument procedure designed according to PANS-OPS. Which assumption is built into the basic PANS-OPS procedure design, and what is the operational consequence?$$,
  $$The procedure assumes engine-out climb performance, so no operator contingency planning is needed.$$,
  $$The procedure assumes all engines are operating; abnormal and emergency contingency procedures remain the operator's responsibility.$$,
  $$The procedure assumes radar vectoring will always be available after take-off.$$,
  $$The procedure assumes visual obstacle avoidance below MSA.$$,
  $$B$$,
  $$Doc 8168 Volume I makes an important distinction: the published flight procedure is a normal-operation procedure. It is not, by itself, an engine-failure escape procedure. This matters especially on departure and missed approach, because obstacle protection is based on the design assumptions of the published procedure. If an engine failure or other abnormal situation occurs, the operator must have contingency procedures suitable for the aircraft, runway and obstacle environment. Therefore, a pilot should not assume that the published SID automatically protects an engine-out aircraft after V1 unless the operator has specifically assessed it.$$,
  $$ICAO Doc 8168 Vol I, Foreword 1.6; Part II, Section 1, Chapter 1, 1.1.1; Part II, Section 2, Chapter 1, 1.2.1$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$General requirements$$,
  $$A procedure is published as tracks or bearings. What is the pilot expected to do in wind?$$,
  $$Fly the published heading without correction, because procedure protection is based on heading.$$,
  $$Maintain the published track or bearing by applying heading corrections for known or estimated wind.$$,
  $$Only correct for wind during the final approach segment.$$,
  $$Request radar vectors whenever the wind correction exceeds 5 degrees.$$,
  $$B$$,
  $$PANS-OPS procedures are fundamentally built around protected tracks or bearings, not around a single fixed heading to be flown in all winds. The pilot is expected to compensate for known or estimated wind so the aircraft remains on the intended protected ground track. This is important because obstacle protection is related to the designed protected area around the nominal track. A heading-only mindset can take the aircraft towards the edge of protection, especially during departure, arrival, holding and non-radar segments.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 1, Chapter 1, 1.1.2; Part II, Section 2, Chapter 1, 1.3.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Obstacle clearance$$,
  $$In a straight segment with track guidance, how is obstacle clearance applied across primary and secondary areas?$$,
  $$Full MOC is provided across the whole width, including both secondary areas.$$,
  $$Full MOC is provided in the primary area; in secondary areas it reduces from the inner edge to zero at the outer edge.$$,
  $$No MOC is provided in the primary area; it is only applied in secondary areas.$$,
  $$MOC is constant in secondary areas but reduced in the primary area.$$,
  $$B$$,
  $$This is one of the key PANS-OPS protection concepts. In straight guided segments, the protected airspace is divided symmetrically around the centreline: the primary area occupies one-half of the total width and each secondary area one-quarter. The full minimum obstacle clearance applies in the primary area. In the secondary areas, protection tapers outward and reaches zero at the outer edge. Operationally, this reinforces why accurate tracking matters: being displaced towards the secondary area may reduce the obstacle margin available.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 1, Chapter 1, 1.3.1 to 1.3.4; Figure II-1-1-1$$,
  $$/question-assets/icao-doc8168/primary-secondary-areas.svg$$
),
(
  $$ICAO Doc 8168$$,
  $$Obstacle clearance$$,
  $$During a turn specified by the procedure where no track guidance is provided, how is the protected area treated?$$,
  $$The whole area is considered primary area.$$,
  $$Only the inner half of the turn is considered primary area.$$,
  $$The turn is protected only after the aircraft rolls out on the next segment.$$,
  $$The area is divided into one primary and four secondary areas.$$,
  $$A$$,
  $$When there is no track guidance during a procedure turn, PANS-OPS treats the entire width of the area as primary. That means full obstacle clearance is intended across the whole protected turning area. This is different from a straight guided segment, where primary and secondary areas are separated. The reason is operational: without positive track guidance in the turn, the aircraft's actual path is more variable, so the design cannot rely on the pilot being centred on a narrow nominal track.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 1, Chapter 1, 1.3.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$FMS/RNAV use$$,
  $$When may FMS/RNAV equipment be used to fly a conventional procedure?$$,
  $$Only if the procedure is published as RNAV.$$,
  $$Only if ATC approves the use of GPS overlays.$$,
  $$It may be used if the procedure is monitored on the basic display normally associated with that procedure and raw-data tolerances are complied with.$$,
  $$It may replace all raw-data monitoring whenever the database contains the procedure.$$,
  $$C$$,
  $$Doc 8168 permits FMS/RNAV use on conventional procedures, but not as a reason to abandon the conventional monitoring basis. The pilot must still monitor using the basic display normally associated with the procedure and remain within the tolerances applicable to raw-data flight. This is a subtle but important operational point: having the procedure in the FMS does not convert a conventional VOR/NDB/ILS procedure into a PBN procedure, and it does not remove the need to check the underlying navigation guidance.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 1, Chapter 1, 1.4.1$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$PBN turns$$,
  $$In PBN procedures, which set correctly describes possible waypoint or turn types used for turning points?$$,
  $$Fly-by, fly-over, or RF turn.$$,
  $$Only fly-over, because turn anticipation is not allowed in protected procedures.$$,
  $$Only fly-by, because overflying a waypoint is never protected.$$,
  $$DME arc only.$$,
  $$A$$,
  $$Doc 8168 distinguishes turning points at conventional fixes, designated altitudes, and waypoints. In PBN procedures, waypoint-related turns may be fly-by, fly-over, or constant radius arc to a fix, known as RF. The difference is operationally important: a fly-by waypoint requires turn anticipation, a fly-over waypoint is crossed before turning, and an RF leg requires the aircraft to fly a defined curved path with constant radius. These are not interchangeable in the FMS and must match the procedure coding and aircraft capability.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 1, Chapter 1, 1.5; Figures II-1-1-2, II-1-1-3 and II-1-1-4$$,
  $$/question-assets/icao-doc8168/waypoint-turn-types.svg$$
),
(
  $$ICAO Doc 8168$$,
  $$Cold temperature correction$$,
  $$Which published altitudes or heights require pilot-applied cold temperature correction according to Doc 8168?$$,
  $$Only the final approach fix altitude.$$,
  $$Only DA/H or MDA/H.$$,
  $$Initial and intermediate segment altitudes/heights, DA/H or MDA/H, and subsequent missed approach altitudes/heights.$$,
  $$Only altitudes below the transition altitude.$$,
  $$C$$,
  $$Cold temperature can make the aircraft's true altitude lower than the barometric altimeter indicates. Therefore the actual obstacle margin may be less than intended. Doc 8168 places responsibility on the pilot to apply the necessary cold temperature corrections to all published minimum altitudes and heights in both conventional and PBN procedures. This includes initial and intermediate segment minima, DA/H or MDA/H, and subsequent missed approach altitudes or heights. The point is not only the approach minima: the missed approach and earlier segments can also be affected.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 1, Chapter 1, 1.7.1$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Baro-VNAV$$,
  $$For a 3D approach based on baro-VNAV criteria, what protection is built into the final approach path at the minimum charted temperature?$$,
  $$The effective VPA is safeguarded so it will not be less than 2.5 degrees and has been obstacle assessed.$$,
  $$The VPA is ignored because temperature correction is not relevant to baro-VNAV.$$,
  $$The procedure becomes a 2D approach at low temperatures.$$,
  $$Only the lateral path is protected; vertical path protection is not considered.$$,
  $$A$$,
  $$For baro-VNAV approaches, low temperature affects the vertical path because barometric altitude is temperature-sensitive. Doc 8168 explains that the procedure design safeguards the final approach vertical path angle at the minimum temperature published on the chart. Applying the appropriate correction allows the nominal VPA to be flown. In some certified systems, an FMS can apply approved automatic compensation; otherwise the pilot must manually account for it. This is different from assuming the published path remains geometrically unchanged in cold conditions.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 1, Chapter 1, 1.7.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Departure procedures$$,
  $$During departure, when should a pilot normally not accept radar vectors?$$,
  $$Whenever a SID exists, regardless of altitude.$$,
  $$If the aircraft is still below the minimum altitude/height required to maintain obstacle clearance in the event of engine failure, unless the route is non-critical for obstacle clearance.$$,
  $$Only below 400 ft AGL.$$,
  $$Only when flying a PBN departure.$$,
  $$B$$,
  $$Doc 8168 gives an important limitation on departure vectors. A vector can remove the aircraft from the published protected route. Therefore, pilots should not accept vectors unless they are above the minimum altitude or height needed to maintain obstacle clearance in the event of engine failure, or unless the departure route is non-critical with respect to obstacle clearance. This is especially significant between V1 and MSA or the end of the contingency procedure, where the aircraft may have limited performance margins.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 2, Chapter 1, 1.3.4$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Departure obstacle clearance$$,
  $$How does minimum obstacle clearance develop after the departure end of runway in the basic departure model?$$,
  $$It is 75 m at the DER and remains constant.$$,
  $$It is zero at the DER and then increases by 0.8 percent of horizontal distance in the direction of flight, assuming a maximum turn of 15 degrees.$$,
  $$It starts at 300 m above all obstacles within 25 NM.$$,
  $$It is provided only after reaching 120 m above aerodrome elevation.$$,
  $$B$$,
  $$The departure obstacle clearance model begins with zero MOC at the DER. From there, the required margin increases with horizontal distance. This is why early turns, climb gradient and obstacle-limited procedures matter so much: the design assumes a defined geometry and a defined climb profile. During turns, Doc 8168 specifies a fixed MOC of 75 m for aeroplanes, with a different value for Category H. A pilot should not treat the departure as having full obstacle margin immediately after lift-off.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 2, Chapter 1, 1.4.1 and 1.4.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Departure PDG$$,
  $$Unless otherwise published, what procedure design gradient is assumed for an instrument departure?$$,
  $$2.5 percent.$$,
  $$3.0 percent.$$,
  $$3.3 percent.$$,
  $$5.2 percent.$$,
  $$C$$,
  $$The standard departure procedure design gradient is 3.3 percent unless another value is published. If obstacles affect the departure route, a higher PDG may be specified and the altitude or height to which it applies must be promulgated. Operationally, this is not just a chart detail: the pilot must verify that aircraft performance can meet the required climb gradient, converting it to a rate of climb as necessary for the expected groundspeed.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 2, Chapter 1, 1.5.1; Part II, Section 2, Chapter 2, 2.2.1 to 2.2.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$PBN departure$$,
  $$Before flying a PBN departure, which item would make the procedure unusable even if the chart is available?$$,
  $$The departure is not contained in the navigation database.$$,
  $$The departure has an RF leg.$$,
  $$The departure uses RNAV 1.$$,
  $$The departure begins at the DER.$$,
  $$A$$,
  $$For PBN departures, the procedure information is expected to be contained in the aircraft navigation database using WGS-84 coordinates. Doc 8168 states that if the database does not contain the departure procedure, it must not be used. The pilot must also verify approval for the applicable navigation specification, required sensors or restrictions, correct equipment functioning, database validity, and waypoint/segment data against the chart. This prevents manual construction errors and incorrect procedure coding from becoming an operational hazard.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 2, Chapter 1, 1.7.5 and 1.7.6$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Standard instrument departures$$,
  $$For procedure design purposes, where does a SID terminate?$$,
  $$At the transition altitude.$$,
  $$At the first fix, facility or waypoint of the en-route phase following the departure procedure.$$,
  $$At the top of climb.$$,
  $$At the first ATC frequency change.$$,
  $$B$$,
  $$A SID is not simply a climb until cruise. For procedure design purposes, Doc 8168 defines its end at the first fix, facility or waypoint of the en-route phase following the departure. That boundary matters because the obstacle clearance and route design assumptions transition from departure criteria to en-route criteria. It also helps explain why SID charting and FMS coding must clearly connect the departure phase to the en-route structure.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 2, Chapter 2, 2.1.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Turning departures$$,
  $$A departure route requires a turn of more than 15 degrees. Which statement best reflects Doc 8168 assumptions for aeroplanes?$$,
  $$It is still treated as a straight departure if the turn occurs before the DER.$$,
  $$It is a turning departure; straight flight is assumed until at least 120 m or 394 ft, with procedures normally catering for turns at 600 m from the beginning of the runway.$$,
  $$The pilot may turn immediately after lift-off if the FMS commands it.$$,
  $$The turn speed is always unrestricted.$$,
  $$B$$,
  $$Doc 8168 treats departures requiring more than 15 degrees of turn as turning departures. For aeroplanes, straight flight is assumed until an altitude or height of at least 120 m or 394 ft. Procedures normally cater for turns at a point 600 m from the beginning of the runway, although charts may restrict turns until the DER or another specified point. This detail is important because turning early can take the aircraft outside the protected area or before the intended obstacle clearance is available.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 2, Chapter 2, 2.4.1$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Omnidirectional departures$$,
  $$When are omnidirectional departures used, and what is the pilot's responsibility if obstacles prevent their development?$$,
  $$They are used only for PBN SIDs; if obstacles exist, ATC assumes responsibility.$$,
  $$They are used when no suitable navigation aid is available or no track guidance is provided; if obstacles prevent their development, the pilot must ensure ceiling and visibility permit visual obstacle avoidance.$$,
  $$They are used whenever a SID is cancelled by ATC; obstacle clearance is always guaranteed.$$,
  $$They are used only for helicopters.$$,
  $$B$$,
  $$Omnidirectional departures are used where no suitable navigation aid exists or no track guidance is provided. However, they are not always possible. If obstacles do not permit an omnidirectional procedure, the pilot must ensure the weather allows visual obstacle avoidance. Published sectors may also have to be avoided. This is a practical reminder that absence of a detailed route does not automatically mean unrestricted obstacle clearance in every direction.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 2, Chapter 3, 3.1.1 to 3.1.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Terminal arrival altitude$$,
  $$Where TAAs are published for a PBN approach, what do they replace?$$,
  $$The final approach fix altitude.$$,
  $$The 46 km or 25 NM minimum sector altitude.$$,
  $$The missed approach altitude.$$,
  $$The transition altitude.$$,
  $$B$$,
  $$Terminal Arrival Altitudes are associated with PBN approaches, often using a T or Y arrangement with IAFs around the IF. Where published, TAAs replace the 46 km or 25 NM MSA. Each TAA provides obstacle clearance while the aircraft tracks direct to the relevant IAF. This reduces the need for separate distance or azimuth reference to an MSA point, but only if the pilot correctly identifies the applicable TAA area and reference point.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 4, Chapter 2, 2.1.1 to 2.1.8$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Terminal arrival altitude$$,
  $$When transitioning from one TAA to another, what altitude rule applies?$$,
  $$The aircraft may cross the boundary at the lower TAA altitude if already cleared for the approach.$$,
  $$The aircraft must reach or maintain the higher of the two TAA values before crossing the boundary.$$,
  $$The aircraft must descend immediately to the new TAA altitude.$$,
  $$TAA boundaries have no operational relevance once the aircraft is within 25 NM.$$,
  $$B$$,
  $$TAA boundaries can separate areas with different minimum altitudes. Doc 8168 requires the pilot to reach or maintain the higher of the two TAA values before crossing from one TAA to another. This is critical near boundaries, where selecting the wrong IAF or using the wrong bearing/distance reference can lead to premature descent. The pilot must remain contained within the relevant boundaries using bearing and distance to the correct IAF.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 4, Chapter 2, 2.4.1 to 2.4.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Terminal arrival altitude$$,
  $$An aircraft is established within a TAA area and wants to enter the associated approach at the IAF. When may it do so without a procedure turn?$$,
  $$Only if ATC issues radar vectors.$$,
  $$If the angle of turn at the IAF does not exceed 110 degrees.$$,
  $$Only if the aircraft is flying an RF leg.$$,
  $$Never; a reversal procedure is always required from a TAA.$$,
  $$B$$,
  $$Doc 8168 permits direct entry from a TAA to the associated approach procedure at the IAF without a procedure turn when the turn angle at the IAF does not exceed 110 degrees. If that condition cannot be met, a reversal procedure must be flown. Operationally, this means the pilot may need to manoeuvre within the TAA before reaching the IAF to establish a suitable inbound track rather than forcing an excessive turn at the fix.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 4, Chapter 2, 2.4.4 and 2.4.5$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Non-precision approach$$,
  $$Which vertical path control technique is preferred on non-precision approaches, and why?$$,
  $$Step-down descent, because it maximizes time at MDA.$$,
  $$CDFA, because it supports stabilized approach principles, reduces workload and reduces the possibility of error.$$,
  $$Level flight at MDA, because it gives the pilot more time to acquire visual references.$$,
  $$Any technique is equally preferred if the MAPt is respected.$$,
  $$B$$,
  $$Doc 8168 identifies controlled flight into terrain risk as high on non-precision approaches and discourages the traditional step-down technique as more error-prone. CDFA is preferred because it converts the final approach into a continuous, stabilized descent profile without level-offs. The technique can use VNAV guidance or manually calculated descent rate, but it must still ensure crossing at or above any step-down fix minimum altitude. The safety value is reduced workload and better vertical situational awareness.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 1, 1.8.1 and 1.8.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Non-precision approach$$,
  $$When flying CDFA on a non-precision approach, what must be done if required visual references have not been acquired approaching MDA/H?$$,
  $$Level off below MDA/H until the MAPt.$$,
  $$Initiate the vertical climbing portion of the missed approach early enough above MDA/H to avoid descending through MDA/H.$$,
  $$Continue descent to the runway threshold and decide at 50 ft.$$,
  $$Ignore the MAPt and turn immediately.$$,
  $$B$$,
  $$With CDFA, the aircraft is descending continuously rather than levelling at MDA/H. Therefore, if visual reference is not acquired approaching MDA/H, the pilot must start the vertical missed approach early enough to prevent the aircraft from passing below MDA/H. This is a subtle but critical point: CDFA does not authorize descent below MDA/H without visual reference, and a delayed go-around from a continuous descent could momentarily infringe the minimum altitude.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 1, 1.8.2.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Non-precision approach$$,
  $$Regardless of the vertical path technique used on a non-precision approach, when may the lateral turning portion of the missed approach be executed?$$,
  $$Immediately after deciding to go around.$$,
  $$Before the MAPt only if the aircraft is above MDA/H.$$,
  $$Not before the MAPt.$$,
  $$Whenever VNAV guidance is used.$$,
  $$C$$,
  $$Doc 8168 separates the vertical decision to discontinue descent from the lateral protection of the missed approach. Even if the missed approach is initiated early in the vertical sense, the lateral turning portion must not be executed before the MAPt. This keeps the aircraft within the protected approach airspace until it reaches the point from which the missed approach protection is designed to begin.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 1, 1.8.6; Part II, Section 5, Chapter 7, 7.1.8.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Baro-VNAV$$,
  $$On a non-precision approach where baro-VNAV is used only as advisory guidance to facilitate CDFA, what altitude/height is the operation conducted to?$$,
  $$The original MDA/H directly, with no decision concept.$$,
  $$A derived DA/H calculated by the operator, based on the MDA/H, and not lower than the MDA/H.$$,
  $$The OCA/H only.$$,
  $$A DA/H selected by ATC.$$,
  $$B$$,
  $$Doc 8168 distinguishes APV procedures, where baro-VNAV is required for the 3D operation, from non-precision procedures where baro-VNAV may be used as advisory vertical guidance to help fly CDFA. In the latter case, the lateral guidance remains based on the charted navigation system, and the operator calculates a derived DA/H based on the MDA/H. That derived DA/H must not be lower than the MDA/H. This prevents advisory VNAV from being treated as if it lowered the published minima.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 1, 1.9.1$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Approach descent gradient$$,
  $$What is the optimum descent gradient or angle used wherever possible for descent procedures?$$,
  $$3.3 percent or 2.0 degrees.$$,
  $$5.2 percent or 3.0 degrees.$$,
  $$2.5 percent or 1.5 degrees.$$,
  $$15 percent or 8.5 degrees.$$,
  $$B$$,
  $$Doc 8168 states that, wherever possible, descent procedures are planned with an optimum gradient of 5.2 percent, equivalent to 3.0 degrees. This is not just a theoretical number: procedure altitudes and heights support stabilized descent profiles and CFIT prevention. When gradients increase, descent rates can become demanding; Doc 8168 gives the example that at 150 kt, a maximum gradient can result in about 1 000 ft/min. The pilot should consider the required rate before starting the approach.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 1, 1.10.1 to 1.10.5$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Missed approach$$,
  $$How many missed approach procedures are established for each instrument approach procedure, and why is this important?$$,
  $$One; it provides defined obstacle protection throughout the missed approach manoeuvre.$$,
  $$Two; one for precision and one for non-precision approaches.$$,
  $$One for each aircraft category.$$,
  $$None; the missed approach is always assigned tactically by ATC.$$,
  $$A$$,
  $$Doc 8168 states that only one missed approach procedure is established for each instrument approach procedure. It specifies where the missed approach begins and where it ends, either at a point or altitude/height. This matters because the obstacle protection is designed around that published procedure. Improvising a different lateral path, especially before the MAPt, can take the aircraft outside protected airspace.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 7, 7.1.1 and 7.1.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Missed approach$$,
  $$On a 2D approach, what must the pilot understand about descent below MDA/H?$$,
  $$Obstacle protection continues normally below MDA/H during approach and missed approach.$$,
  $$Descent below MDA/H shall not be made without required visual reference, and no obstacle or terrain protection is provided below MDA/H during the approach or missed approach.$$,
  $$Descent below MDA/H is allowed if the aircraft is before the MAPt.$$,
  $$The MDA/H applies only to the final approach segment before the FAF.$$,
  $$B$$,
  $$This is a key operational trap. On a 2D approach, the pilot may not descend below MDA/H without the required visual reference. Doc 8168 further warns that obstacle or terrain protection is not provided when descending below MDA/H during the approach or missed approach. Therefore, going below MDA/H is not just a matter of seeing something; it requires the correct visual reference and a position from which the landing can be completed safely.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 7, 7.1.4$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Missed approach$$,
  $$If a missed approach is initiated before the MAPt, what lateral path should be flown?$$,
  $$Turn immediately to the missed approach heading.$$,
  $$Continue the lateral tracking of the approach until reaching the MAPt, then follow the published missed approach.$$,
  $$Proceed direct to the holding fix.$$,
  $$Fly runway heading until ATC gives vectors.$$,
  $$B$$,
  $$An early go-around does not automatically mean an early missed-approach turn. Doc 8168 instructs the pilot to continue the lateral tracking of the approach until the MAPt, then follow the missed approach as published. This keeps the aircraft inside the protected approach area until the missed approach protection begins. The aircraft may cross the MAPt above the required altitude or height, but lateral sequencing remains tied to the MAPt.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 7, 7.1.8.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Missed approach$$,
  $$What is the normal minimum missed approach climb gradient for aeroplanes, and what extra caution does Doc 8168 give?$$,
  $$3.3 percent; all aircraft can always meet it.$$,
  $$2.5 percent; it may not be usable by all aircraft at high gross mass or in non-normal configurations.$$,
  $$5.2 percent; it is the same as the final approach descent angle.$$,
  $$0.8 percent; it begins at the DER.$$,
  $$B$$,
  $$Normal missed approach procedures are based on a 2.5 percent minimum climb gradient for aeroplanes. Doc 8168 warns that even this nominal gradient, or higher gradients, may not be achievable by all aircraft at high gross mass or in non-normal configurations such as engine-out. At obstacle-critical aerodromes, this can require special procedures and possibly increased DA/H or MDA/H. Therefore, missed approach climb capability is an operational performance issue, not merely a chart annotation.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 7, 7.1.9.1 to 7.1.9.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Circling$$,
  $$After initial visual contact during a circling approach, what must be maintained?$$,
  $$Only sight of the approach lights.$$,
  $$The runway environment must be kept in sight, the aircraft must remain within the visual manoeuvring area, and it must not descend below circling MDA/H.$$,
  $$Only the runway centreline extension must be kept in sight.$$,
  $$The aircraft may leave the visual manoeuvring area if visual reference is maintained.$$,
  $$B$$,
  $$Circling is a visual manoeuvre following an instrument approach, but it is not unrestricted manoeuvring. After visual contact, the runway environment must remain in sight, the aircraft must stay within the visual manoeuvring area, and descent below circling MDA/H is not allowed until the required conditions are met. The runway environment includes identifiable features such as the threshold, approach lighting or other runway-related markings.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 6, 6.2.1 and 6.2.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Circling$$,
  $$During circling, when should descent below MDA/H not be made?$$,
  $$Until required visual reference is established and maintained, the landing threshold is in sight, obstacle clearance can be maintained, and the aircraft is positioned for landing using normal descent rates and bank angles.$$,
  $$Only until the runway lights are seen momentarily.$$,
  $$Until ATC clears the aircraft to land.$$,
  $$Until the aircraft is abeam the threshold, regardless of visual reference.$$,
  $$A$$,
  $$Doc 8168 sets multiple conditions for descent below circling MDA/H. Required visual reference must be established and maintained throughout the manoeuvre, the landing threshold must be in sight, obstacle clearance must be maintained, and the aircraft must be in a position to land using normal rates of descent and bank. This prevents a pilot from descending below MDA/H based on a fleeting visual cue or from an unstable position.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 6, 6.3.3$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Circling missed approach$$,
  $$If visual reference is lost while circling to land, what should the pilot do?$$,
  $$Continue visually in the last known runway direction.$$,
  $$Follow the missed approach for that instrument procedure, initially using a climbing turn within the circling area towards the landing runway before intercepting the published missed approach.$$,
  $$Proceed direct to the IAF at the last assigned altitude.$$,
  $$Descend to regain visual reference.$$,
  $$B$$,
  $$Loss of visual reference in circling is handled by returning to the instrument missed approach protection. Doc 8168 says the missed approach specified for the particular procedure must be followed. The transition should begin with a climbing turn within the circling area towards the landing runway, then interception and execution of the published missed approach. Airspeed must not exceed the maximum associated with visual manoeuvring.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 5, Chapter 6, 6.4.1$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Holding$$,
  $$In conventional holding, what bank angle or rate of turn should be used?$$,
  $$30 degrees or 5 degrees per second, whichever is greater.$$,
  $$25 degrees or 3 degrees per second, whichever requires the lesser bank.$$,
  $$15 degrees fixed bank only.$$,
  $$Rate one only, regardless of bank angle.$$,
  $$B$$,
  $$Doc 8168 specifies that holding turns are made at 25 degrees of bank or 3 degrees per second, whichever requires the lesser bank. This matters because holding protected areas assume certain aircraft performance and turn behaviour. At higher speeds or altitudes, rate and bank limitations influence the actual ground track and the ability to remain inside the holding protection area.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 6, Chapter 2, 2.1.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Holding$$,
  $$When does outbound timing begin in a conventional holding pattern?$$,
  $$Immediately after crossing the fix.$$,
  $$Over or abeam the fix, whichever occurs later; if abeam cannot be determined, when the turn to outbound is completed.$$,
  $$Only after wings are level inbound.$$,
  $$At the end of the outbound leg.$$,
  $$B$$,
  $$Outbound timing is not always simply started at the fix. Doc 8168 specifies that timing begins over or abeam the fix, whichever occurs later. If the abeam position cannot be determined, timing starts when the turn to outbound is completed. This prevents the outbound leg from being shortened incorrectly when the aircraft's turn geometry delays the abeam position or makes it difficult to identify.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 6, Chapter 2, 2.1.4$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Holding$$,
  $$A holding outbound leg is based on a limiting DME distance. When does the outbound leg terminate?$$,
  $$When the published time expires, regardless of DME.$$,
  $$As soon as the limiting DME distance is reached.$$,
  $$Only when ATC instructs the aircraft to turn inbound.$$,
  $$At the next crossing of the holding radial.$$,
  $$B$$,
  $$When a holding procedure uses a DME distance to define the outbound leg, the distance is controlling. The outbound leg terminates as soon as the limiting DME distance is reached. This is different from a purely timed hold. If the aircraft waits until a timed value after reaching the limiting distance, it may exceed the protected holding area.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 6, Chapter 2, 2.1.5$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Holding$$,
  $$What flexibility is recognized at the boundaries between the three standard holding entry sectors?$$,
  $$No flexibility is allowed.$$,
  $$5 degrees on either side of the sector boundaries.$$,
  $$10 degrees only on the direct-entry boundary.$$,
  $$15 degrees on either side of all boundaries.$$,
  $$B$$,
  $$Holding entries are based on the aircraft heading relative to three entry sectors. Doc 8168 recognizes a 5-degree zone of flexibility on either side of the sector boundaries. This avoids over-precision at sector boundaries and acknowledges real-world heading and wind variation. It does not mean the pilot can disregard the entry sectors entirely; it only provides limited flexibility around the boundary lines.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 6, Chapter 2, 2.2.2$$,
  null
),
(
  $$ICAO Doc 8168$$,
  $$Holding$$,
  $$For outbound entry heading in holding, what still-air time should not normally be exceeded?$$,
  $$30 seconds below 14 000 ft and 1 minute above.$$,
  $$1 minute at or below 14 000 ft, and 1.5 minutes above 14 000 ft.$$,
  $$2 minutes at all altitudes.$$,
  $$1.5 minutes below 14 000 ft and 1 minute above.$$,
  $$B$$,
  $$Doc 8168 gives outbound entry heading time limits for holding. At or below 4 250 m or 14 000 ft, the still-air time should not exceed one minute. Above that level, it should not exceed one and one-half minutes. These values are part of keeping the aircraft within the designed entry and holding protection area, especially when wind correction and turn geometry are considered.$$,
  $$ICAO Doc 8168 Vol I, Part II, Section 6, Chapter 2, 2.2.9.1$$,
  null
);
